spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/oopproject"
    username: "oopproject"
    password: "oopproject"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
